# Generated by Django 2.2.6 on 2019-10-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20191015_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='products',
            field=models.ManyToManyField(limit_choices_to=5, related_name='company_products', to='leads.Product'),
        ),
    ]
