# Generated by Django 2.2.6 on 2019-10-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20191021_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
